const lessonTitle = "刻舟求剑";

const lessonData = [
    // ===== 文言文 =====
    ["楚", "chǔ", "Chu", "Chu", "楚国的"],
    ["人", "rén", "person", "orang", "有个"],
    ["有", "yǒu", "there was", "ada", "有"],
    ["涉江者", "shè jiāng zhě", "one who crossed the river", "orang yang menyeberangi sungai", "渡江的人"],
    ["，", "", "", "", ""],
    ["其", "qí", "his", "dia punya", "他的"],
    ["剑", "jiàn", "sword", "pedang", "剑"],
    ["自", "zì", "from", "dari", "从"],
    ["舟中", "zhōu zhōng", "boat", "perahu", "船上"],
    ["坠", "zhuì", "fell", "jatuh", "掉"],
    ["于", "yú", "into", "ke dalam", "到"],
    ["水", "shuǐ", "water", "air", "水里"],
    ["，", "", "", "", ""],
    ["遽", "jù", "quickly", "segera", "急忙"],
    ["契", "qì", "carved a mark", "mengukir tanda", "刻"],
    ["其", "qí", "his", "dia punya", "他的"],
    ["舟", "zhōu", "boat", "perahu", "船上"],
    ["，", "", "", "", ""],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["是", "shì", "this", "ini", "这里"],
    ["吾", "wú", "my", "saya punya", "我的"],
    ["剑", "jiàn", "sword", "pedang", "剑"],
    ["之所从坠", "zhī suǒ cóng zhuì", "where it fell from", "tempat jatuhnya", "掉下去的地方"],
    ["。”", "", "", "", ""],
    ["舟", "zhōu", "The boat", "Perahu", "船"],
    ["止", "zhǐ", "stopped", "berhenti", "停了"],
    ["，", "", "", "", ""],
    ["从", "cóng", "from", "dari", "从"],
    ["其所契者", "qí suǒ qì zhě", "the place where he carved the mark", "tempat dia mengukir tanda", "他刻记号的地方"],
    ["入", "rù", "enter", "masuk", "跳入"],
    ["水", "shuǐ", "water", "air", "水里"],
    ["求之", "qiú zhī", "seek it", "mencarinya", "寻找剑"],
    ["。", "", "", "", ""],
    ["舟", "zhōu", "The boat", "Perahu", "船"],
    ["已", "yǐ", "already", "sudah", "已经"],
    ["行矣", "xíng yǐ", "moved", "bergerak", "向前走了"],
    ["，", "", "", "", ""],
    ["而", "ér", "but", "tetapi", "而"],
    ["剑", "jiàn", "the sword", "pedang", "剑"],
    ["不行", "bù xíng", "did not move", "tidak bergerak", "没有移动"],
    ["，", "", "", "", ""],
    ["求剑若此", "qiú jiàn ruò cǐ", "seeking the sword like this", "mencari pedang seperti ini", "像这样找剑"],
    ["，", "", "", "", ""],
    ["不亦", "bù yì", "isn't it", "bukankah", "不也"],
    ["惑乎", "huò hū", "confused", "keliru", "糊涂吗"],
    ["！", "", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["《", "", "", "", ""],
    ["吕氏春秋", "lǚ shì chūn qiū", "Lüshi Chunqiu", "Lüshi Chunqiu", "吕氏春秋"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
